services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
