version: '3'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}